version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/java/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"

  - package-ecosystem: "gomod"
    directory: "/go/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"
