version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/java/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"
    commit-message:
      prefix: "maven"
      include: "scope"

  - package-ecosystem: "gomod"
    directory: "/go/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"
    commit-message:
      prefix: "gomod"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "nothub"
    commit-message:
      prefix: "github-actions"
      include: "scope"
