name: '🚔'
on: [ push, pull_request ]
jobs:

  test-go:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: 'test'
        working-directory: ./go
        run: go test ./...

  test-java:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          check-latest: true
          cache: 'maven'
      - name: 'test'
        working-directory: ./java
        run: mvn --batch-mode --show-version --errors verify --file pom.xml
